eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/  # Eureka Server URL with the new port
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Expose Actuator endpoints
