eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/  # Eureka Server URL with the new port
    registerWithEureka: true
    fetchRegistry: true

  instance:
    hostname: localhost
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
