#eureka:
  #instance:
   # hostname: localhost
  #  prefer-ip-address: true
 # client:
  #  fetch-registry: false
   # register-with-eureka: false
    #service-url:
  #    defaultZone: http://localhost:9090/eureka

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY-URL:http://localhost:9090/eureka}
