eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/  # Eureka Server URL with the new port


# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:9090/eureka/  # Eureka Server URL with the new port
#     registerWithEureka: true
#     fetchRegistry: true

# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'  # Customize which endpoints are exposed
#   endpoint:
#     health:
#       show-details: always  # Control detail level of the health endpoint
